name: BSD

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Test
      uses: cross-platform-actions/action@v0.22.0
      with:
        operating_system: freebsd
        version: '13.2'
        memory: 8G
        sync_files: runner-to-vm
        run: |
          sudo pkg install -y go121
          go121 test -v ./...
