name: Cross compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Test
      run: gormlite/test.sh
