name: Reproducible build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: .github/workflows/repro.sh
