name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-qemu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: { lfs: 'true' }

    - uses: actions/setup-go@v5
      with: { go-version: stable }

    - uses: docker/setup-qemu-action@v3

    - name: Test s390x
      run: GOARCH=s390x go test -v -short ./...
